version: "1"
pipelines:
  - name: pipeline:10.10.10
    description: pipeline production test 4
    env:
      static:
        - DOCKER_REGISTRY=ghcr.io
        - GITHUB_ORG=my-org-name
        - GITHUB_REPO=my-repo
      secrets:
        - DOCKER_REGISTRY_USER
        - DOCKER_REGISTRY_PASS
    events:
      - "github:CampbellBrett/pipeline:pull_request.merged"
      - "github:CampbellBrett/pipeline:pull_request.opened"
      - "github:CampbellBrett/pipeline:pull_request.synchronize"
    jobs:
      - name: pipeline-build
        description: example build step
        packages:
          - git
          - npm
        steps:
          - npm i
          - npm run test
